### PR TITLE
update wording

### PR DESCRIPTION
**Pull request by theaeonsolution**

### CODE REVIEW

**Comment by thestinger** [comment]
@theaeonsolution Needs to be rebased now due to merging the other one.

**Comment by theaeonsolution** [comment]
> @theaeonsolution Needs to be rebased now due to merging the other one.

Let me fix that. Thanks.

**Comment by theaeonsolution** [comment]
@thestinger ready!

**Comment by thestinger** [comment]
I'm not sure this change fully preserves the desired meaning of the sentence. I agree with rewording it but it probably needs to be changed a bit from this.

**Comment by thestinger** [comment]
I'm not sure this change fully preserves the desired meaning of the sentence. I agree with rewording it but it probably needs to be changed a bit from this.

**Comment by theaeonsolution** [comment]
Understood. Closing the pull request for now.

**Pull request closed without merging**
