### PR TITLE
Clarify enabling developer options.

### PR DESCRIPTION
**Pull request by Forbo**

### CODE REVIEW

**Comment by thestinger** [comment]
This needs to be kept in sync across both guides.

**Comment by Forbo** [comment]
I've done the same for the CLI guide now as well.

**Comment by thestinger** [comment]
The tense here doesn't matter the rest of the sense. It also doesn't really match what's said afterwards.

**Comment by thestinger** [comment]
Used this wording instead: https://github.com/GrapheneOS/grapheneos.org/commit/2a08a0cfea73cd2c5e2086e80847110261b5ccd4.

**Pull request closed without merging**
