### PR TITLE
IRC Rules

### PR DESCRIPTION
**Pull request by louipc**
Old IRC rules server is out of service. Might as well upload to graphene.org
This also includes a rewording to more direct language.

### CODE REVIEW

**Comment by louipc** [comment]
Guess I should ping @Peter-Easton for input here.

**Comment by Peter-Easton** [comment]
Sorry about that. I had to take down my VPS because I broke something and I haven't had the time to fix it yet. It looks good.

**Comment by louipc** [comment]
Any concerns, chance of merging? @thestinger

**Comment by louipc** [comment]
Gonna see if I can pivot these elsewhere.

**Pull request closed without merging**
