### PR TITLE
 Add an overflow-x:auto; for the table

### PR DESCRIPTION
**Pull request by c2tz**

### CODE REVIEW

**Comment by thestinger** [comment]
@1c2t1z This needs to use the standalone CSS file since inline CSS isn't permitted by the Content Security Policy.

**Comment by c2tz** [comment]
@thestinger ouch I hadn't thought about that. No way to add a hash `'sha256-+/8l6fxQyrdundiK66ViWS5VlHiQUAi4V/Ir8XXFYh0='` in the csp with the integrity of the <style>? If not, I'll see if I can make a media query (but it will change the look of the array) it will be a bit more complicated as you said at the beginning. Because this method with the div can only work inline.

**Comment by x86pup** [comment]
@1c2t1z It would require allowing unsafe-hashes which is still not wanted.

**Comment by thestinger** [comment]
@1c2t1z You should be able to just give the div an id but I don't really understand why a div is required at all.

**Comment by c2tz** [comment]
I tried based on this [example](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_table_responsive) to add the overflow in the table class but it does not give the expected result

**Comment by c2tz** [comment]
ok i found it in fact only with a div associated with an overflow that we can have the scroll bar (i don't know why) i will make the modifications and redo my pull request properly.

**Pull request closed without merging**
