### PR TITLE
Donate page design improvements

### PR DESCRIPTION
**Pull request by tedgravlin**
This is the initial draft of design improvements for the Donate page.
I focused on making the page be a better use of vertical space. The old design is spaced out and requires a lot of scrolling to see the same amount of info.

| Desktop | Mobile |
| ------------- | ------------- |
| image | image  |
| image | image |

I still need to implement another 'learn more' page and cleanup some code, but I wanted to get some feedback first.

Thanks!

### CODE REVIEW

**Comment by matchboxbananasynergy** [comment]
The immediate issue I see with this is that it seems to be using an obsolete Paypal link.

Even if changing the style of this page is desired (unsure if it is), we need to make sure that all of the same information is being conveyed, and that the links are up to date.

**Comment by flawedworld** [comment]
Please resubmit without changing whitespace of unrelated items on the page. Commits also need to be neatened please. Otherwise I like the look of this initially, we need to add a few more options to the donation page too.

**Comment by flawedworld** [comment]
Validation checks also need to pass.

**Comment by tedgravlin** [comment]
> @matchboxbananasynergy: The immediate issue I see with this is that it seems to be using an obsolete Paypal link.

I can definitely fix that! I did the bulk of the work before the new payment links were added, so I need to go back and fix them. I just wanted to get this drafted up so I could get some feedback while I was continuing to work on it.
 
Thanks!

**Comment by tedgravlin** [comment]
> @flawedworld: Please resubmit without changing whitespace of unrelated items on the page. 

My apologies, I forgot to fix the couple of lines I had to change to get things working on my end. When the PR is ready I'll make sure to get all of that inline!

> Commits also need to be neatened please.

Could you be more specific about what needs to be done? I'm a little new to PR's on GitHub so an explanation would be helpful. Thanks!

>Validation checks also need to pass.

Absolutely! I'll make sure everything is good to go before the PR is ready.

**Comment by tedgravlin** [comment]
@flawedworld I'm having difficulties with the validation checks. I've run my code through multiple different validators and they don't find any issues. I'm probably missing something obvious, but any help would be greatly appreciated.

I also addressed the issues above, let me know what else I can do! 
Thanks :)

cc @matchboxbananasynergy

**Comment by flawedworld** [comment]
@tedgravlin We will not accept a PR with merge commits in it, and we would prefer to have commits be atomic in fashion - they should incrementally change things and make it clear what is being changed.

The validation checks are correct in stating that there is an issue. HTML is unfortunately very permissive and so whilst it may parse correctly in the DOM of a browser, it does not mean that it is following strict hygiene and adherence to the HTML standard.

**Comment by tedgravlin** [comment]
I'm gonna give a go at rewriting the code in hopes that it fixes the validation issues.

**Comment by tedgravlin** [comment]
I'm gonna close this PR and open a new one without all of the errors.

**Pull request closed without merging**
