### PR TITLE
Update platform-tools to 34.0.3

### PR DESCRIPTION
**Pull request by Displax**

### CODE REVIEW

**Comment by thestinger** [comment]
@Displax This is likely going to get merged, there is someone that's going to work on testing it.

**Comment by Displax** [comment]
Found some issues in this release:
https://issuetracker.google.com/issues/284327750
https://issuetracker.google.com/issues/284616650
https://issuetracker.google.com/issues/284335462

So r33.0.3 still most stable at this moment.

**Comment by thestinger** [comment]
Ah, we ran into some of that with the newly built 34.0.1 and we thought they would have fixed it. The original 34.0.1 was fine, but they reuploaded it with a broken release...

**Comment by Klaas-** [comment]
34.0.3 seems to work here, I've successfully flashed via cli to a nexus 7a, but you need to set ANDROID_PRODUCT_OUT variable ( https://issuetracker.google.com/issues/284327750 )

**Pull request closed without merging**
